services:
  postgres:
    image: 'postgres:alpine3.18'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
  