server:
  port: ${SERVER_PORT}
jwt:
  SECRET_KEY: ${JWT_SECRET:my_s3cr3t_k3y}
  DURATION: ${JWT_TIMEOUT:10} # jwt duration in minutes
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  flyway:
    enabled: true
  docker:
    compose:
      lifecycle-management: none
      enabled: false


#documentation
springdoc:
  api:
    docs:
      enabled: false
  swagger-ui:
    enabled: false
    path: /doc/swagger-ui.html
  
  